 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/deputies", type: :request do
  # Deputy. As you add validations to Deputy, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Deputy.create! valid_attributes
      get deputies_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      deputy = Deputy.create! valid_attributes
      get deputy_url(deputy)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_deputy_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      deputy = Deputy.create! valid_attributes
      get edit_deputy_url(deputy)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Deputy" do
        expect {
          post deputies_url, params: { deputy: valid_attributes }
        }.to change(Deputy, :count).by(1)
      end

      it "redirects to the created deputy" do
        post deputies_url, params: { deputy: valid_attributes }
        expect(response).to redirect_to(deputy_url(Deputy.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Deputy" do
        expect {
          post deputies_url, params: { deputy: invalid_attributes }
        }.to change(Deputy, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post deputies_url, params: { deputy: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested deputy" do
        deputy = Deputy.create! valid_attributes
        patch deputy_url(deputy), params: { deputy: new_attributes }
        deputy.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the deputy" do
        deputy = Deputy.create! valid_attributes
        patch deputy_url(deputy), params: { deputy: new_attributes }
        deputy.reload
        expect(response).to redirect_to(deputy_url(deputy))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        deputy = Deputy.create! valid_attributes
        patch deputy_url(deputy), params: { deputy: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested deputy" do
      deputy = Deputy.create! valid_attributes
      expect {
        delete deputy_url(deputy)
      }.to change(Deputy, :count).by(-1)
    end

    it "redirects to the deputies list" do
      deputy = Deputy.create! valid_attributes
      delete deputy_url(deputy)
      expect(response).to redirect_to(deputies_url)
    end
  end
end
