default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password:
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: dev_password
  database: app_development
test:
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: dev_password
  database: app_test
production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>